language: rust
sudo: false

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev

rust:
  - nightly
  - beta
  - stable

before_script:
  - cargo install cargo-kcov
  - cargo kcov --print-install-kcov-sh | $SHELL

script:
  - |
      cargo build &&
      cargo kcov --coveralls &&
      cargo bench &&
      cargo doc

after_success: |
  [ "${TRAVIS_BRANCH}" = master ] &&
  [ "${TRAVIS_PULL_REQUEST}" == false ] &&
  [ "${TRAVIS_RUST_VERSION}" == stable ] &&
  cargo install ghp &&
  ghp target/doc &&
  git config user.name "Travis Documentation" &&
  git config user.email "name@example.com" &&
  git push -qf https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages 2>&1 > /dev/null

env:
  global:
    - secure: "TwGRf6pujZ+g2eye0ypGTlZBNuLfkItt6ubCcddafRE7W7T66CV/SwrF1rreaGd2DTrXW1Zkqag8M5SW36qCG+VpzpX8+BkERZmQTkJrZtJ8PdF0ry5D156xuz0B5f1nuzuGLvYwZNQpfxzUCy7KPW6/tCgyS826LqqFbb6CaMM="
